name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]   # Läuft bei jedem Push auf main
  workflow_dispatch:      # Optional: manuelles Auslösen

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: 18
  DIST_PATH: build   # <--- anpassen, falls dein Output z.B. 'dist' heißt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # SPA-Fallback für Deep Links
      - name: Add SPA fallback
        if: always()
        run: |
          if [ -f "${{ env.DIST_PATH }}/index.html" ]; then
            cp "${{ env.DIST_PATH }}/index.html" "${{ env.DIST_PATH }}/404.html"
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIST_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
